[build]
  command = "node build.js"
  publish = "dist"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[context.dev.environment]
  NODE_ENV = "development"
